### ISSUE TITLE
[Scheduled Maintenance] Banner Upgrades 

### ISSUE THREAD

**Issue by rjayadeva** [ccri-ops/system-status#26]
## Scheduled Maintenance: Banner and ODS

**Service Impact:** Ellucian Banner

**Maintenance Window:**
- **Banner Maintenance:**
  - **Start:** 2024-07-27 9:00 PM EDT, Saturday, 7/27
  - **End:** 2024-07-27 2:00 AM EDT, Sunday, 7/28
- **ODS Maintenance:**
  - **Start:** 2024-07-27 9:00 PM EDT, Saturday, 7/27
  - **End:** 2024-07-28 4:00 PM EDT, Sunday, 7/28

**Impact:**
Banner will be undergoing maintenance from 9 PM EDT on Saturday, July 27 until 2 AM EDT on Sunday, July 28. Additionally, in alignment with this, there will be ODS maintenance from 9 PM EDT on Saturday, July 27 until 4 PM EDT on Sunday, July 28.

**Service Interruption:**
This maintenance will cause a service interruption to Banner Application Navigator, Administrative Pages, and Jobs.

**Comment by greend139** [comment]
## Scheduled Maintenance: Banner and ODS

**Service Impact:** Ellucian Banner

**Maintenance Window:**
- **Banner Maintenance:**
  - **Start:** 2024-07-27 9:00 PM EDT, Saturday, 7/27
  - **End:** 2024-07-27 2:00 AM EDT, Sunday, 7/28
- **ODS Maintenance:**
  - **Start:** 2024-07-27 9:00 PM EDT, Saturday, 7/27
  - **End:** 2024-07-28 4:00 PM EDT, Sunday, 7/28

**Impact:**
Banner will be undergoing maintenance from 9 PM EDT on Saturday, July 27 until 2 AM EDT on Sunday, July 28. Additionally, in alignment with this, there will be ODS maintenance from 9 PM EDT on Saturday, July 27 until 4 PM EDT on Sunday, July 28.

**Service Interruption:**
This maintenance will cause a service interruption to Banner Application Navigator, Administrative Pages, and Jobs.
