### ISSUE TITLE
[Service Interruption] Verizon Phone Service Interruption Warwick Campus

### ISSUE THREAD

**Issue by rjayadeva** [ccri-ops/system-status#34]
We are currently experiencing a service interruption with Verizon phone services at the Warwick campus. For any emergency calls, please use your mobile device. We apologize for any inconvenience and are working actively with Verizon to restore phone service as soon as possible.

**Comment by greend139** [comment]
We are currently experiencing a service interruption with Verizon phone services at the Warwick campus. For any emergency calls, please use your mobile device. We apologize for any inconvenience and are working actively with Verizon to restore phone service as soon as possible.

**Comment by greend139** [comment]
Phone service has been restored.
