### ISSUE TITLE
Microsoft Services Slow 

### ISSUE THREAD

**Issue by rjayadeva** [ccri-ops/system-status#39]
We are currently aware of login slowness affecting Microsoft services. We are actively monitoring the situation and is in communication with Microsoft to resolve the issue.

We will provide updates as soon as more information becomes available. We appreciate your patience and understanding.

**Comment by greend139** [comment]
Microsoft has provided an update: 
_The fix which is addressing impact is continuing to deploy and has now reached 98 percent of the affected environment. Regarding recovery, we've encountered delays in our targeted restarts; however, we're identifying alternative options to expedite recovery of the affected infrastructure._

**Comment by greend139** [comment]
Issue has been resolved.
